#! /bin/bash

set -e
set -o pipefail

fail () {
	yad --error --title="$1" --text="$2" --center
	return 1
}

GAMEDIR=lemmings-christmas-demo

if [ ! -d $SNAP_USER_DATA/$GAMEDIR/demo ];
then
	echo "Game directory does not exist"
	echo "Creating directory"
	mkdir -p $SNAP_USER_DATA/$GAMEDIR
	echo "Copying game to directory"
	cd $SNAP_USER_DATA/$GAMEDIR
	wget https://archive.org/download/LemmingsChristmasDemoPsygnosis1991/Lemmings_Christmas_Demo_Psygnosis_1991.zip -t 5 --timeout 10 2>&1 | \
	perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Downloading... \2 (\3)/' | \
	yad --progress --title="Downloading Lemmings" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape \
	|| fail "Network Error" "Could not access network to download game files.\nPlease check the network status."
	unzip -d demo Lemmings_Christmas_Demo_Psygnosis_1991.zip \
	|| fail "Error" "Could not extract game files.\nThe download may have been corrupted"
fi

cd $SNAP_USER_DATA/$GAMEDIR
dosbox demo/TGALEMMI.EXE -exit -machine tandy -scaler normal3x
