name: lemmings-christmas
version: '0.1'
summary: Lemmings Christmas shareware demo
description: |
  Lemmings Christmas demo by DMA design, with the dosbox emulator

grade: stable
confinement: strict
parts:
  launch:
    after: [ desktop-glib-only ]
    plugin: dump
    source: launcher
    stage-packages:
      - wget
      - unzip
      - libpng12-0
      - libsdl1.2debian
      - libgl1-mesa-glx
      - libsdl-net1.2
      - libsdl-sound1.2
      - dosbox
      - libglu1-mesa
      - yad
      - perl-base
    prime:
      - -share
      - -usr/share/doc
      - -usr/share/lintian
      - -usr/share/man
      - -usr/share/icons

apps:
  lemmings-christmas:
    plugs: [unity7, pulseaudio, opengl, network, x11, joystick]
    command: desktop-launch $SNAP/launcher
